nuigurumi03/freemarket_sample_65e

app/assets/stylesheets/_in-header.scss
app/assets/stylesheets/_out-header.scss
app/assets/stylesheets/_profile.scss
app/assets/stylesheets/_reset.scss
app/views/layouts/_in-header.html.haml
app/views/layouts/_out-header.html.haml

#why
ヘッダーファイルの部分テンプレート設定
#what
ファイル管理の簡素化のため

[WIP]ヘッダーファイル編集

---

app/assets/stylesheets/_buy-products.scss
app/views/layouts/application.html.haml
app/views/products/show.html.haml
config/breadcrumbs.rb

#what
パンくず機能実装
#why
パンくずテスト作成のため

[WIP]パンくず作成

---

app/assets/stylesheets/exhibition.scss
app/views/layouts/exhibition.html.haml

why
出品フォームの追加
what
フォームから
出品出来る様にするため

exhibition-formの追加

---

app/controllers/users_controller.rb

#what
users.controllerにshowアクションを追加
#why
プロフィール画面実装のため

users.controllerにshowアクション追加

---

app/assets/stylesheets/_out-header.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/profile.scss
app/views/users/_profile.html.haml
app/views/users/show.html.haml

#what
プロフィールビューを作成
#why
プロフィール機能実装のため

プロフィールビュー作成

---

app/controllers/products_controller.rb
app/views/products/index.html.haml

#what
データベースから商品一覧に必要な情報を表示する
#why
データの処理が正しく行われているか確認するため

[WIP]商品一覧にデータ取得、表示

---

spec/controllers/products_controller_spec.rb

#what
商品一覧表示に関するモデルと、コントローラーのテスト
#why
商品一覧表示機能の実装確認のため

[WIP]商品一覧表示の単体テスト

---

app/assets/stylesheets/users_index.scss
app/controllers/users_controller.rb
app/views/users/_mypage.html.haml
config/routes.rb

[What]
user-mypageの実装
[Why]
必要なため

user-mypageの実装

---

app/models/address.rb
app/models/prefecture.rb
db/migrate/20191230111232_create_addresses.rb
db/schema.rb
spec/factories/addresses.rb
spec/models/address_spec.rb

what 
都道府県をデーターで扱うため
activ hashに変更
why
出品フォームに埋め込むため

"都道府県　activ hash""

---

db/migrate/20191225051109_create_products.rb
db/migrate/20191225064038_create_user_details.rb
db/migrate/20191230111232_create_addresses.rb
db/schema.rb

テーブル　カラム名　ある程度修正

---

app/assets/stylesheets/profile.scss
app/views/users/_top.html.haml
app/views/users/profile.html.haml

商品購入確認画面のhamlとサイドバーのhamlを組み合わせる
商品購入確認画面の実装を完了させるため

[WIP]商品購入確認画面にサイドバーを反映させる

---

app/assets/stylesheets/_buy-products.scss
app/controllers/products_controller.rb
app/views/products/show.html.haml

[WIP]商品購入確認画面実装

---

app/assets/stylesheets/logout.scss
app/assets/stylesheets/profile.scss
app/views/layouts/_breadcrumbs.html.haml
app/views/layouts/application.html.haml
app/views/users/logout.html.haml
app/views/users/profile.html.haml
config/breadcrumbs.rb

[WIP]パンくず機能実装

---

app/assets/stylesheets/step1.scss
app/assets/stylesheets/step3.scss
app/views/signup/step1.html.haml

step1画面の大まかview

---

app/assets/stylesheets/_buy-products.scss

[WIP]プロフィールページのヘッダー、フッター修正

---

app/assets/stylesheets/_buy-products.scss
app/assets/stylesheets/signup.scss
app/assets/stylesheets/step1.scss
app/assets/stylesheets/step2.scss
app/assets/stylesheets/step3.scss
app/assets/stylesheets/step4.scss
app/assets/stylesheets/users_index.scss
app/controllers/signup_controller.rb
app/views/signup/new.html.haml
app/views/signup/step1.html.haml
app/views/signup/step1e.html.haml
app/views/signup/step2.html.haml
app/views/signup/step3.html.haml
app/views/signup/step4.html.haml

ウィザード新規登録修正

---

app/controllers/products_controller.rb
app/models/prefecture.rb
app/models/product.rb
app/views/products/new.html.haml
db/migrate/20191225051109_create_products.rb

[What]
prefectureがデータベースに保存されるようにする
[Why]
データが反映するようにするため

prefecture実装

---

app/models/product.rb
app/views/products/new.html.haml
db/migrate/20191225051109_create_products.rb

[What]
sqlの値を文字に変更、エラー文表示
[Why]
見やすくするため

sqlの値を文字に変更

---

app/assets/javascripts/channels/facebook-sdk.js
app/controllers/signup_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
app/views/devise/registrations/step1.html.haml
app/views/signup/step1.html.haml
config/routes.rb

what:
SNS認証　実装
https://gyazo.com/ae2fa50b8bac818a5ae24368672d55fd
URLは登録フォームに移った初期状態から値が入っているかの映像です。
データベースに値入ります。
why:
ログインの手間を省くため。

原因はbuild_user_detail　忘れるな！

---

app/controllers/card_controller.rb
app/models/user.rb
app/views/card/add.html.haml
app/views/card/edit.html.haml
app/views/card/show.html.haml
app/views/layouts/application.html.haml
config/breadcrumbs.rb
config/routes.rb
db/migrate/20200108031258_create_cards.rb
db/schema.rb

payjp完了(前半)

---

app/assets/javascripts/application.js
app/controllers/signup_controller.rb
app/views/signup/step3.html.haml

what  
step3.haml書き直し。
why 
payjpの属性を受け渡すために　form_withで書き直す必要があるため

カード登録 view

---

app/assets/stylesheets/exhibition.scss
app/controllers/products_controller.rb
app/views/products/new.html.haml

[What]
category, bland,ビュー修正
[Why]
エラー発火時のビュー修正、sqlへのデータ反映

category,brand,ビュー修正

---

app/views/products/edit.html.haml
app/views/products/new.html.haml

what
商品編集ページ、画像投稿機能
why
商品編集ページで必要

商品編集　image

---

app/controllers/step_controller.rb
app/views/step/new.html.haml

payjpの過程でとりあえず一度stepコントローラーを作成しました。
viewも　newとして残しています。

一応step コントローラー

---

app/controllers/products_controller.rb
app/views/products/detail.html.haml
app/views/products/show.html.haml
app/views/users/listing.html.haml
spec/models/product_spec.rb

子カテゴリー、孫カテゴリーは商品出品時、編集時に選択できますが、商品詳細には反映されません。

カテゴリーjs実装修正
